### PR TITLE
Add support for Windows

### PR DESCRIPTION
**Pull request by extant1**
Add support for Windows

Fix is from @Shimada666 closing out #2, I've made the changes discussed in #4 and attaching video recording showing the issue and the changes in a windows environment.

https://www.youtube.com/watch?v=JeIf87pEfb0

Edit:  Sorry if I did this wrong as I didn't see a way to commit to the other pull request.

### CODE REVIEW

**Comment by nickjj** [comment]
Hi,

Thanks a lot for the PR.

You know, after looking at the old PR and the issues at hand, would it be even easier if we didn't use `os.path.relpath`? What if we just used string interpolation and hard coded the `/` as a separator. I didn't test this in Linux or Windows, but something like `rel_file_path = f"{file}/{output_path}"`.

Or if that doesn't end up working, what about a string replace on `\\` to `/` like ` rel_file_path = os.path.relpath(file, output_path).replace("\\", "/")`?

**Comment by extant1** [comment]
I tried the first option and it won't work without extra code to work on the paths but the latter works perfectly and is the more elegant option between all of them.

**Comment by extant1** [comment]
Pay no attention to the commit hiding behind the curtain.

**Comment by nickjj** [comment]
Hi,

Is there any chance you can destroy this PR, and make a new one with the latest passing code with a `Add support for Windows` commit message?

**Pull request closed without merging**
